#!/bin/sh

make clean;
make;
sudo make install;

psql <<EOF
	DROP EXTENSION dump_fcinfo;
	CREATE EXTENSION dump_fcinfo;

	\timing
	\echo
	\echo

	\echo SELECT dump_fcinfo();
	SELECT dump_fcinfo();

	\echo
	\echo

	\echo SELECT * FROM dump_fcinfo();
	SELECT * FROM dump_fcinfo();
	
	\echo
	\echo
	
	\echo SELECT * FROM dump_fcinfo() LIMIT 5;
	SELECT * FROM dump_fcinfo() LIMIT 5;
	
	\echo
	\echo

	\echo SELECT dump_fcinfo() FROM ( VALUES (1) ) AS t(x);
	SELECT dump_fcinfo() FROM ( VALUES (1) ) AS t(x);
EOF
